# Generated by Django 5.2.7 on 2025-10-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clínico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='orden',
        ),
    ]
