# Generated by Django 5.2.7 on 2025-11-18 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clínico', '0002_tema_interrogacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['nombre'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterModelOptions(
            name='paciente_ficticio',
            options={'ordering': ['nombre'], 'verbose_name': 'Paciente Ficticio', 'verbose_name_plural': 'Pacientes Ficticios'},
        ),
        migrations.AlterModelOptions(
            name='partes_del_cuerpo',
            options={'ordering': ['nombre'], 'verbose_name': 'Parte del Cuerpo', 'verbose_name_plural': 'Partes del Cuerpo'},
        ),
        migrations.DeleteModel(
            name='Tema_Interrogacion',
        ),
    ]
