# Generated by Django 5.2.7 on 2025-11-18 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Estudiante', '0002_alter_progreso_estudiante_and_more'),
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.docente'),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
