# Generated by Django 5.2.7 on 2025-11-18 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_alter_curso_docente_delete_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Docente')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del Docente')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo del Docente')),
                ('contrasena', models.CharField(max_length=150, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.docente'),
        ),
    ]
