# Generated by Django 5.2.7 on 2025-11-18 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_docente_alter_curso_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendizaje_esperado',
            options={'ordering': ['nombre'], 'verbose_name': 'Aprendizaje Esperado', 'verbose_name_plural': 'Aprendizajes Esperados'},
        ),
        migrations.AlterModelOptions(
            name='categoria_clinica',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría Clínica', 'verbose_name_plural': 'Categorías Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['nombre'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='apellido',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
