# Generated by Django 5.2.7 on 2025-11-18 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0001_initial'),
        ('Evaluaciones', '0002_alter_evaluacion_estudiante_envio_docente'),
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.estudiante'),
        ),
        migrations.AlterField(
            model_name='solicitud_inscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.estudiante'),
        ),
        migrations.AlterField(
            model_name='solicitud_inscripcion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.docente'),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
