# Generated by Django 5.2.7 on 2025-11-18 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0002_alter_progreso_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Estudiante')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del Estudiante')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo del Estudiante')),
                ('contrasena', models.CharField(max_length=150, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='progreso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='solicitud_inscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante'),
        ),
    ]
