# Generated by Django 5.2.7 on 2025-11-18 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_docente_alter_curso_docente'),
        ('Estudiante', '0003_estudiante_alter_progreso_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_inscripcion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.docente'),
        ),
    ]
