# Generated by Django 5.2.7 on 2025-11-18 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0004_alter_solicitud_inscripcion_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='progreso',
            options={'ordering': ['id'], 'verbose_name': 'Progreso', 'verbose_name_plural': 'Progresos'},
        ),
        migrations.AlterModelOptions(
            name='solicitud_inscripcion',
            options={'ordering': ['id'], 'verbose_name': 'Solicitud de Inscripción', 'verbose_name_plural': 'Solicitudes de Inscripción'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
