# Generated by Django 5.2.7 on 2025-10-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Envíos', '0001_initial'),
        ('Evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_docente',
            name='respuesta_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.respuesta_evaluacion'),
        ),
    ]
