# Generated by Django 5.2.7 on 2025-11-18 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluaciones', '0001_initial'),
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.estudiante'),
        ),
        migrations.CreateModel(
            name='Envio_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la evaluación:')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nombreestudiante', models.TextField(verbose_name='Nombre estudiante:')),
                ('fechaentrega', models.DateField(verbose_name='Fecha de entrega')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.docente')),
                ('respuestaevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluaciones.respuesta_evaluacion')),
            ],
        ),
    ]
