# Generated by Django 5.2.7 on 2025-11-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0005_alter_estudiante_options_alter_progreso_options_and_more'),
        ('Evaluaciones', '0002_alter_evaluacion_estudiante_envio_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='respuesta_evaluacion',
            options={'ordering': ['id'], 'verbose_name': 'Respuesta Evaluación', 'verbose_name_plural': 'Respuestas Evaluaciones'},
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante'),
        ),
        migrations.DeleteModel(
            name='Envio_Docente',
        ),
    ]
